"""
Action scoring and evaluation system.

This file can be auto-generated by the Parameter Tuning GUI.
Parameters are loaded from config/default_params.yml.
"""

from core.actions import Action
from core.state import RobotState
from config.loader import PARAMS

# TUNED PARAMETERS (loaded from config)
SAFETY_WEIGHT = PARAMS['safety_weight']
HELPFULNESS_WEIGHT = PARAMS['helpfulness_weight']
CRITICAL_BATTERY = PARAMS['critical_battery']
RECHARGE_THRESHOLD = PARAMS['recharge_threshold']
HELP_MIN_BATTERY = PARAMS['help_min_battery']


def score_action(action: Action, state: RobotState) -> float:
    """
    Evaluate how good an action is in the current state.
    
    This implementation uses tuned weights to balance safety and helpfulness.
    """
    
    safety_score = score_safety(action, state)
    helpfulness_score = score_helpfulness(action, state)
    
    # Weighted combination using tuned weights
    total = safety_score * SAFETY_WEIGHT + helpfulness_score * HELPFULNESS_WEIGHT
    
    return total


def score_safety(action: Action, state: RobotState) -> float:
    """Score based on safety (battery management)."""
    score = 50.0
    
    if action == Action.HELP_USER:
        # Penalize helping when battery is low
        if state.battery < CRITICAL_BATTERY:
            score -= 100
        elif state.battery < HELP_MIN_BATTERY:
            score -= 50
        elif state.battery < RECHARGE_THRESHOLD:
            score -= 20
        else:
            score += 30
    
    elif action == Action.RECHARGE:
        # Reward recharging based on need
        if state.battery < CRITICAL_BATTERY:
            score += 100
        elif state.battery < RECHARGE_THRESHOLD:
            score += 70
        elif state.battery < 60:
            score += 30
        else:
            score -= 10
    
    elif action == Action.WAIT:
        score -= 20  # Generally discourage waiting
    
    elif action == Action.CALL_FOR_HELP:
        score += 10  # Safe but not preferred
    
    return score


def score_helpfulness(action: Action, state: RobotState) -> float:
    """Score based on helpfulness to user."""
    score = 0.0
    
    urgency_multiplier = [0, 1.5, 3.0, 5.0]
    
    if action == Action.HELP_USER:
        base_score = 100
        score = base_score * urgency_multiplier[state.user_urgency]
        
        # Bonus for good battery
        if state.battery > RECHARGE_THRESHOLD:
            score += 40
    
    elif action == Action.RECHARGE:
        score = 20  # Necessary but delays help
        
        if state.user_urgency >= 3:
            score -= 80  # Bad to delay critical help
        elif state.user_urgency >= 2:
            score -= 40
        
        # But necessary if low battery
        if state.battery < CRITICAL_BATTERY:
            score += 60
    
    elif action == Action.WAIT:
        if state.user_urgency == 0:
            score = 10
        else:
            score = -50  # Bad to wait when user needs help
    
    elif action == Action.CALL_FOR_HELP:
        if state.user_urgency >= 2:
            score = 30
        else:
            score = -30
    
    return score


def score_efficiency(action: Action, state: RobotState) -> float:
    """Score based on efficiency."""
    # Optional: implement efficiency scoring
    return 0.0
